spring:
  application:
    name: trip-planner
#  output:
#    ansi:
#      enabled: ALWAYS
  config:
    import: "classpath:overpass-queries.yml"


default:
  country: India
  state: Uttar Pradesh
  city: Varanasi
  noOfPlaces: 5

#logging:
#  level:
#    root: INFO
#    com.shri.spring.ai.tripplanner: DEBUG
#    com.shri.spring.ai.tripplanner.service.impl.PlaceServiceImpl: TRACE
#    org.springframework.web: WARN
#    org.hibernate: ERROR

