spring:
  application:
    name: trip-planner
  threads:
    virtual:
      enabled: true
  #  output:
#    ansi:
#      enabled: ALWAYS
  config:
    import: "classpath:overpass-queries.yml"


management:
  endpoints:
    web:
      exposure:
        include: "*"



default:
  country: India
  state: Uttar Pradesh
  city: Varanasi
  noOfPlaces: 5

api:
  openmeteo:
    url: https://api.open-meteo.com/v1
  wikidata:
    url: https://www.wikidata.org/w/api.php
  wikimedia:
    url: https://commons.wikimedia.org/wiki/Special:FilePath
#logging:
#  level:
#    root: INFO
#    com.shri.spring.ai.tripplanner: DEBUG
#    com.shri.spring.ai.tripplanner.service.impl.PlaceServiceImpl: TRACE
#    org.springframework.web: WARN
#    org.hibernate: ERROR

